# Generated by Django 5.1 on 2024-09-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_collaborator_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
