# Generated by Django 5.1 on 2024-09-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_collaborator_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='photo',
            field=models.BinaryField(editable=True),
        ),
    ]
