# Generated by Django 5.1 on 2024-08-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0002_alter_collaborator_edv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collaborator',
        ),
    ]
